services:
  mysql:
    image: "mysql:8"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: "1234"
      MYSQL_DATABASE: "graph_db"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p1234" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  legalian-take-home:
    build: .
    ports:
      - "8000:8000"
    restart: "unless-stopped"
    environment:
      # PORT: "8000"
      APP_DB_HOST: "mysql"
      APP_DB_PORT: 3306
      APP_DB_USER: "root"
      APP_DB_PASSWORD: "1234"
      APP_DB_NAME: "graph_db"
    networks:
      - internal
    depends_on:
      mysql:
        condition: "service_healthy"

networks:
  internal:

volumes:
  mysql-data: