services:
  mysql:
    image: "mysql:8"
    restart: "always"
    environment:
      MYSQL_ROOT_PASSWORD: ${APP_DB_PASSWORD}
      MYSQL_DATABASE: ${APP_DB_NAME}
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - internal
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u${APP_DB_USER}", "-p${APP_DB_PASSWORD}" ]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 30s

  legalian-take-home:
    build: .
    ports:
      - "8000:${PORT}"
    restart: "unless-stopped"
    environment:
      PORT: ${PORT}
      APP_DEBUG_MODE: ${APP_DEBUG_MODE}
      APP_DB_HOST: ${APP_DB_HOST}
      APP_DB_PORT: ${APP_DB_PORT}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_PASSWORD: ${APP_DB_PASSWORD}
      APP_DB_NAME: ${APP_DB_NAME}
    networks:
      - internal
    depends_on:
      mysql:
        condition: "service_healthy"

networks:
  internal:

volumes:
  mysql-data: